Change allow superuser to edit future posts
blancltd/blanc-news pull request #5
Opened 2016-10-27 15:10 UTC by zatan

Fixes https://github.com/blancltd/django-glitter-news/issues/2

2016-10-28 13:25 UTC, tomkins requested changes
Will be nice to get this fixed!

2016-10-28 13:25 UTC, tomkins commented on glitter_news/views.py
> +        if self.request.user.is_superuser:
Think we need to open this to users other than superusers.

Can we change this to something like:

```python
self.request.user.has_perm('glitter_news.edit_post')
```

Or:

```python
qs = self.get_queryset()
self.request.user.has_perm(
    '{}.edit_{}'.format(qs.model._meta.app_label, qs.model._meta.model_name
)
```

Up to you (and test the second one, I think that's the right format for it).

2016-10-31 11:46 UTC, zatan commented
Updated.

2016-10-31 12:38 UTC, tomkins approved these changes
:shipit: if you want, tweak if you feel it's needed.

2016-10-31 12:38 UTC, tomkins commented on glitter_news/views.py
> +        if self.request.user.is_superuser or self.request.user.has_perm(post_edit_permission):
Do we need the additional check for a superuser? As has_perm will always return True for superusers.

Up to you!

2016-10-31 13:37 UTC, zatan commented
Removed we don't need useless code! :+1:

2016-10-31 13:41 UTC, tomkins commented
Super - :shipit:!

2016-10-31 13:42 UTC, merged